ERROR = "error"
WARNING = "warning"

XNAT_URL = "XNAT_URL"
XNAT_USER = "XNAT_USER"
XNAT_PASSWORD = "XNAT_PASSWORD"
XNAT_PROJECT = "XNAT_PROJECT"

DATA_FOLDER = "DATA_FOLDER"

TASK = "TASK"
CHECK = "CHECK"
TRAIN = "TRAIN"
TASK_ID = "TASK_ID"
