ALGORITHM = "brain_age"

ERROR = "error"
WARNING = "warning"

# Data sources
DB_POSTGRES = "POSTGRES"
DB_CSV = "CSV"

DB_USER = 'DB_USER'
DB_PASSWORD = 'DB_PASSWORD'
DB_HOST = 'DB_HOST'
DB_PORT = 'DB_PORT'
DB_DATABASE = 'DB_DATABASE'
DB_CNN_DATABASE = 'DB_CNN_DATABASE'

TASK_TABLE = "TASK"

XNAT_URL = "XNAT_URL"
XNAT_USER = "XNAT_USER"
XNAT_PASSWORD = "XNAT_PASSWORD"
XNAT_PROJECT = "XNAT_PROJECT"

ID = "id"
SEX = "sex"
AGE = "age"

# Path
DATA_FOLDER = "DATA_FOLDER"
IMAGES_FOLDER = "IMAGES_FOLDER"
MODEL_FOLDER = "MODEL_FOLDER"

IMAGE_SUFFIX = "IMAGE_SUFFIX"
DEFAULT_IMAGE_NAME = "_aseg_GM_to_template_GM_mod.nii.gz"

TASK = "TASK"
CHECK = "CHECK"
TRAIN = "TRAIN"
PREDICT = "PREDICT"
TASK_ID = "TASK_ID"
ORGANIZATION_ID = "ORGANIZATION_ID"
RESULT = "RESULT"
METRICS = "METRICS"

# CNN options
PADDING_SAME="same"
RELU = "relu"

INPUT_SHAPE = "INPUT_SHAPE"
USE_MASK = "USE_MASK"
MASK_FILENAME = "MASK_FILENAME"
MODEL = "MODEL"

TRAINING_IDS = "TRAINING_IDS"
VALIDATION_IDS = "VALIDATION_IDS"
TESTING_IDS = "TESTING_IDS"

# Hyperparameters - Master
ROUNDS = "ROUNDS"
ROUND = "ROUND"
MASTER = "MASTER"
NODE = "NODE"

# Hyperparameteres
LEARNING_RATE = "LEARNING_RATE"
BETA1 = "BETA1"
BETA2 = "BETA2"
EPSILON = "EPSILON"
DECAY = "DECAY"
USE_PADDING = "USE_PADDING"
CROP_INDEXES = "CROP_INDEXES"
AUGMENT_TRAIN = "AUGMENT_TRAIN"
IMG_SCALE = "IMG_SCALE"
BATCH_SIZE = "BATCH_SIZE"
PATIENTS_PER_EPOCH = "PATIENTS_PER_EPOCH"
EPOCHS = "EPOCHS"

# Other configurations
GPU_COUNT = "GPU_COUNT"
DB_TYPE = "DB_TYPE"
MAX_NUMBER_TRIES = "MAX_NUMBER_TRIES"
DEFAULT_MAX_NUMBER_TRIES = 100

# Outcome
WEIGHTS = "WEIGHTS"
SAMPLES = "SAMPLES"
MAE = "mae"
MSE = "mse"
LOSS = "loss"
HISTORY = "HISTORY"

NUMBER_SCANS = "NUMBER_SCANS"
MISSING_SCANS = "MISSING_SCANS"
MESSAGE = "MESSAGE"
